#!/usr/bin/env python3
"""
Generates emv/emv_aid_db.c, emv/emv_country_db.c and emv/emv_currency_db.c
from the official flipperzero-firmware EMV resource files:
  applications/main/nfc/resources/nfc/assets/aid.nfc
  applications/main/nfc/resources/nfc/assets/country_code.nfc
  applications/main/nfc/resources/nfc/assets/currency_code.nfc

These are the same lookup tables the original (pre-2023) built-in EMV reader
used, just baked into flash instead of loaded from SD card resource files at
runtime, so the standalone app is self-contained.

Usage:
    python scripts/gen_emv_tables.py <path-to-flipperzero-firmware-checkout>
"""
import sys
from pathlib import Path

HEADER_NOTE = (
    "// Auto-generated by scripts/gen_emv_tables.py from the official\n"
    "// flipperzero-firmware EMV resource files. Do not edit by hand.\n"
)


def parse_nfc_kv(path: Path):
    entries = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("Filetype") or line.startswith(
            "Version"
        ):
            continue
        key, _, value = line.partition(":")
        entries.append((key.strip(), value.strip()))
    return entries


def gen_aid_db(src: Path, out_dir: Path):
    entries = parse_nfc_kv(src)

    lines = [HEADER_NOTE, '#include "emv_aid_db.h"', "", "#include <stddef.h>", "",
             "typedef struct {", "    const uint8_t* aid;",
             "    uint8_t aid_len;", "    const char* name;", "} EmvAidEntry;", ""]

    byte_arrays = []
    table_rows = []
    for i, (aid_hex, name) in enumerate(entries):
        aid_bytes = bytes.fromhex(aid_hex)
        var = f"emv_aid_bytes_{i}"
        byte_arrays.append(
            "static const uint8_t %s[] = {%s};"
            % (var, ", ".join(f"0x{b:02X}" for b in aid_bytes))
        )
        escaped_name = name.replace("\\", "\\\\").replace('"', '\\"')
        table_rows.append(f'    {{{var}, {len(aid_bytes)}, "{escaped_name}"}},')

    lines.extend(byte_arrays)
    lines.append("")
    lines.append("static const EmvAidEntry emv_aid_table[] = {")
    lines.extend(table_rows)
    lines.append("};")
    lines.append("")
    lines.append(
        "static uint8_t emv_aid_prefix_match_len(\n"
        "    const uint8_t* a,\n"
        "    uint8_t a_len,\n"
        "    const uint8_t* b,\n"
        "    uint8_t b_len) {\n"
        "    uint8_t max_len = a_len < b_len ? a_len : b_len;\n"
        "    uint8_t i = 0;\n"
        "    while(i < max_len && a[i] == b[i]) i++;\n"
        "    return i;\n"
        "}\n"
    )
    lines.append(
        "bool emv_aid_db_lookup(const uint8_t* aid, uint8_t aid_len, const char** name_out) {\n"
        "    const EmvAidEntry* best = NULL;\n"
        "    uint8_t best_match = 0;\n"
        "    for(size_t i = 0; i < sizeof(emv_aid_table) / sizeof(emv_aid_table[0]); i++) {\n"
        "        const EmvAidEntry* entry = &emv_aid_table[i];\n"
        "        if(entry->aid_len == aid_len &&\n"
        "           emv_aid_prefix_match_len(entry->aid, entry->aid_len, aid, aid_len) == aid_len) {\n"
        "            *name_out = entry->name;\n"
        "            return true;\n"
        "        }\n"
        "        uint8_t match = emv_aid_prefix_match_len(entry->aid, entry->aid_len, aid, aid_len);\n"
        "        if(match >= 5 && match > best_match) {\n"
        "            best_match = match;\n"
        "            best = entry;\n"
        "        }\n"
        "    }\n"
        "    if(best) {\n"
        "        *name_out = best->name;\n"
        "        return true;\n"
        "    }\n"
        "    return false;\n"
        "}\n"
    )

    out_path = out_dir / "emv_aid_db.c"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(entries)} AIDs)")


def gen_code_db(src: Path, out_dir: Path, table_name: str, func_name: str, out_file: str, header: str):
    entries = parse_nfc_kv(src)
    # entries are (numeric-code-as-4-digit-string, alpha-code)
    parsed = sorted((int(code, 10), alpha) for code, alpha in entries)

    lines = [HEADER_NOTE, f'#include "{header}"', "", "#include <stddef.h>", "",
              "typedef struct {", "    uint16_t code;",
              "    const char name[4];", f"}} {table_name}Entry;", ""]
    lines.append(f"static const {table_name}Entry {table_name.lower()}_table[] = {{")
    for code, alpha in parsed:
        lines.append(f'    {{{code}, "{alpha}"}},')
    lines.append("};")
    lines.append("")
    lines.append(
        f"bool {func_name}(uint16_t code, const char** name_out) {{\n"
        f"    size_t count = sizeof({table_name.lower()}_table) / sizeof({table_name.lower()}_table[0]);\n"
        f"    size_t lo = 0, hi = count;\n"
        f"    while(lo < hi) {{\n"
        f"        size_t mid = lo + (hi - lo) / 2;\n"
        f"        if({table_name.lower()}_table[mid].code < code) {{\n"
        f"            lo = mid + 1;\n"
        f"        }} else {{\n"
        f"            hi = mid;\n"
        f"        }}\n"
        f"    }}\n"
        f"    if(lo < count && {table_name.lower()}_table[lo].code == code) {{\n"
        f"        *name_out = {table_name.lower()}_table[lo].name;\n"
        f"        return true;\n"
        f"    }}\n"
        f"    return false;\n"
        f"}}\n"
    )

    out_path = out_dir / out_file
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(parsed)} entries)")


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    fw_root = Path(sys.argv[1])
    assets = fw_root / "applications" / "main" / "nfc" / "resources" / "nfc" / "assets"
    out_dir = Path(__file__).resolve().parent.parent / "emv"

    gen_aid_db(assets / "aid.nfc", out_dir)
    gen_code_db(
        assets / "country_code.nfc",
        out_dir,
        "EmvCountry",
        "emv_country_db_lookup",
        "emv_country_db.c",
        "emv_country_db.h",
    )
    gen_code_db(
        assets / "currency_code.nfc",
        out_dir,
        "EmvCurrency",
        "emv_currency_db_lookup",
        "emv_currency_db.c",
        "emv_currency_db.h",
    )


if __name__ == "__main__":
    main()
